name: demo1
description: 典典的小卖部,淘客版本 qq群667186542
version: 3.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.9"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.4
  supercharged: ^2.1.1
  flutter_syntax_view: ^4.0.0
  date_format: ^2.0.7
  dio: ^5.4.0
  flutter_spinkit: ^5.2.0
  tab_indicator_styler: ^2.0.0
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.3
  common_utils: ^2.1.0
  extended_image: ^8.2.0
  waterfall_flow: ^3.0.3
  extended_list: ^3.0.1
  pull_to_refresh_notification: ^3.1.0
  connectivity_plus: ^5.0.2
  fsearch_nullsafety: ^2.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  extended_text: ^12.0.1
  animated_text_kit: ^4.2.2
  html: ^0.15.4
  extended_tabs: ^4.1.0
  after_layout: ^1.2.0
  palette_generator: ^0.3.3+3
  crypto: ^3.0.3
  encrypt: ^5.0.3
  extended_nested_scroll_view: ^6.2.1
  sliver_tools: ^0.2.12
  shelf: ^1.4.1
  extended_sliver: ^2.1.3
  fcontrol_nullsafety: ^2.0.0
  get_it: ^7.6.7
  logger: ^2.0.2+1
  shelf_proxy: ^1.0.4
  bubble_tab_indicator: ^0.1.6
  badges: ^3.1.2
  carousel_pro_nullsafety: ^2.0.0
  flutter_markdown: ^0.6.18+3
  zefyrka: ^1.5.0
  package_info: ^2.0.2
  show_up_animation: ^2.0.0
  hive: ^2.2.3
  flutter_swiper_null_safety_flutter3: ^4.0.3
  path_provider: ^2.1.2
  hooks_riverpod: ^2.4.10
  flutter_smart_dialog: ^4.9.6
  hive_flutter: ^1.1.0
  flutter_widget_from_html_core: ^0.14.11
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  keyboard_actions: ^4.2.0
  fast_immutable_collections: ^10.1.0
  flutter_slidable: ^3.0.1
  loading_more_list_fast: ^7.0.7
  loading_more_list_library_fast: ^4.0.6
  dd_js_util: ^6.0.5
  dd_models: ^0.1.0
  dd_check_plugin: ^3.1.4
  dataoke_sdk: ^4.0.9
  permission_handler: ^11.2.0
  go_router: ^13.1.0
  responsive_builder: ^0.7.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  webview_flutter: ^4.5.0
  async: ^2.11.0
  share_plus: ^7.2.2
  blurrycontainer: ^1.0.2
  scoped_model: ^2.0.0

  # ume工具
  flutter_ume_plus: ^3.0.1
  flutter_ume_kit_dio_plus: ^3.4.4
  flutter_ume_kit_show_code_plus: ^3.0.0
  flutter_ume_kit_device_plus: ^2.0.0
  flutter_ume_kit_console_plus: ^2.0.2
  flutter_ume_kit_perf_plus: ^2.0.0
  flutter_ume_kit_channel_monitor_plus: ^2.0.0
  flutter_ume_kit_ui_plus: ^2.0.0


dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator_plus: ^3.0.4


dependency_overrides:
  watcher: ^1.1.0
  flutter_lints: ^3.0.1
  meta: ^1.11.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/