name: demo1
description: 典典的小卖部,淘客版本 qq群667186542
version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.4"


dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.11
  supercharged: ^2.1.1
  flutter_syntax_view: ^4.0.0
  date_format: ^2.0.7
  dio: ^5.2.1+1
  flutter_spinkit: ^5.2.0
  tab_indicator_styler: ^2.0.0
  flutter_easyrefresh: ^2.2.2
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.3
  common_utils: ^2.1.0
  extended_image: ^8.0.2
  waterfall_flow: ^3.0.2
  extended_list: ^3.0.0
  pull_to_refresh_notification: ^3.0.1
  connectivity_plus: ^4.0.1
  fsearch_nullsafety: ^2.0.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.7
  extended_text: ^11.0.1
  animated_text_kit: ^4.2.2
  html: ^0.15.4
  extended_tabs: ^4.1.0
  after_layout: ^1.2.0
  palette_generator: ^0.3.3+2
  crypto: ^3.0.3
  encrypt: ^5.0.1
  extended_nested_scroll_view: ^6.1.0
  sliver_tools: ^0.2.10
  shelf: ^1.4.1
  extended_sliver: ^2.1.3
  fcontrol_nullsafety: ^2.0.0
  flutter_hooks: ^0.18.6
  get_it: ^7.6.0
  logger: ^1.4.0
  shelf_proxy: ^1.0.4
  bubble_tab_indicator: ^0.1.6
  badges: ^3.1.1
  carousel_pro_nullsafety: ^2.0.0
  flutter_markdown: ^0.6.15
  zefyrka: ^1.4.0
  package_info: ^2.0.2
  show_up_animation: ^2.0.0
  hive: ^2.2.3
  flutter_blurhash: ^0.7.0
  flutter_swiper_null_safety_flutter3: ^3.0.1
  path_provider: ^2.0.15
  hooks_riverpod: ^2.3.6
  flutter_smart_dialog: ^4.9.2
  hive_flutter: ^1.1.0
  flex_color_scheme: ^7.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  keyboard_actions: ^4.2.0
  fast_immutable_collections: ^9.1.5
  flutter_slidable: ^3.0.0
  loading_more_list_fast: ^6.0.1
  loading_more_list_library_fast: ^3.0.1
  extended_text_field: ^12.0.1
  dd_js_util:
    path: ../dd_js_util
  dd_models:
    path: ../plugins/dataoke_sdk/dd_models
  dd_check_plugin:
    path: ../../hlx/github/dd_check_plugin
  dataoke_sdk:
    path: ../plugins/dataoke_sdk
  permission_handler: ^10.3.0
  go_router: ^8.0.5
  responsive_builder: ^0.7.0
  image_picker: ^0.8.9


dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/

