name: demo1
description: 典典的小卖部,淘客版本 qq群667186542
version: 2.1.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.5
  url_launcher: ^6.1.6
  supercharged: ^2.1.1
  flutter_syntax_view: ^4.0.0
  date_format: ^2.0.7
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  tab_indicator_styler: ^2.0.0
  provider: ^6.0.4
  flutter_easyrefresh: ^2.2.2
  fbutton_nullsafety: ^5.0.0
  fsuper_nullsafety: ^3.0.3
  common_utils: ^2.1.0
  extended_image: ^6.3.2
  waterfall_flow: ^3.0.2
  loading_more_list: ^5.0.2
  extended_list: ^3.0.0
  pull_to_refresh_notification: ^2.3.0
  fsearch_nullsafety: ^2.0.0
  carousel_slider: ^4.1.1
  shimmer: ^2.0.0
  flutter_svg: ^1.1.6
  extended_text_field: ^10.1.1
  extended_text: ^9.1.2
  animated_text_kit: ^4.2.2
  html: ^0.15.1
  extended_tabs: ^4.0.1
  after_layout: ^1.2.0
  palette_generator: ^0.3.3+2
  crypto: ^3.0.2
  encrypt: ^5.0.1
  extended_nested_scroll_view: ^5.1.3
  sliver_tools: ^0.2.8
  shelf: ^1.4.0
  extended_sliver: ^2.1.3
  fcontrol_nullsafety: ^2.0.0
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  logger: ^1.1.0
  http: ^0.13.5
  shelf_proxy: ^1.0.2
  responsive_builder: ^0.4.3
  bubble_tab_indicator: ^0.1.6
  badges: ^2.0.3
  carousel_pro_nullsafety: ^1.0.2
  flutter_markdown: ^0.6.13
  zefyrka: ^1.3.0
  package_info: ^2.0.2
  show_up_animation: ^2.0.0
  hive: ^2.2.3
  flutter_blurhash: ^0.7.0
  curl_logger_dio_interceptor: ^0.0.3
  flutter_swiper_null_safety_flutter3: ^3.0.0
  path_provider: ^2.0.11
  riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  dd_check_plugin: ^1.0.0
  flutter_smart_dialog: ^4.7.0+1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.1.1
  flex_color_scheme: ^6.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  loading_animation_widget: ^1.2.0+3
  hive_generator: ^2.0.0
  keyboard_actions: ^4.1.0
  dd_js_util: ^2.0.1
  dataoke_sdk: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  analyzer: any
  freezed: any
  json_serializable: ^6.5.4




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/

